---
# tasks file for ansible-role-landir.gnome_conf
- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure packages installed
  apt:
    name:
      - dconf-cli
      - gnome-shell
      - gnome-shell-extensions
      - python3-psutil
    state: present
  when: ansible_os_family == 'Debian'

- name: Gnome theme
  dconf:
    key: "{{ item.chave }}"
    value: "{{ item.valor | string }}"
  with_items: "{{ configuracoes }}"
  become_user: "{{ gnome_usuario }}"
  become: false

- name: Terminal theme
  shell: |
    perfil_uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | sed "s/'//g" )
    key_perfil=`echo "{{ item | string }}" | sed "s/\([^ ]*\) \(.*\)/\1/"`
    value_perfil=`echo "{{ item | string }}" | sed "s/\([^ ]*\) \(.*\)/\2/"`
    echo "debug: key_perfil $key_perfil"
    echo "debug: value_perfil $value_perfil"
    valor_atual=`gsettings get "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$perfil_uuid/" $key_perfil`
    echo "debug: valor_atual $valor_atual"
    valor_atual=`echo $valor_atual | sed "s/'//g'"`
    value_perfil=`echo $value_perfil | sed "s/'//g'"`
    if [ "$value_perfil" != "$valor_atual" ] ; then
      gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$perfil_uuid/" {{ item | string }}
    else
      echo "nothing changed"
    fi
  with_items: "{{ terminal }}"
  register: saida_ver
  changed_when: saida_ver.stdout is not search('nothing changed')
  become_user: "{{ gnome_usuario }}"
  become: false

- name: No animations
  command: gsettings get org.gnome.desktop.interface enable-animations
  changed_when: false
  become_user: "{{ gnome_usuario }}"
  become: false

- name: No auto updates
  lineinfile:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Update-Package-Lists'
    line: 'APT::Periodic::Update-Package-Lists "0";'
    state: present
  become: true

- name: Opt-out tracker
  command: gsettings set org.freedesktop.Tracker.Miner.Files {{ item }}
  with_items:
    - enable-monitors false
    - ignored-files "['*']"
    - crawling-interval -2
  changed_when: false
  become_user: "{{ gnome_usuario }}"
  become: false

- name: Stop the Tracker
  command: tracker daemon -k
  changed_when: false
  become_user: "{{ gnome_usuario }}"
  become: false

- name: Opt-out popularity-contest
  lineinfile:
    dest: /etc/popularity-contest.conf
    regexp: '^PARTICIPATE'
    line: 'PARTICIPATE="no"'
    state: present
  become: true

- name: Clean Tracker and popularity-contest
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.cache/tracker
    - ~/.local/share/tracker
    - ~/.cache/ubuntu-report
  become_user: "{{ gnome_usuario }}"
  become: false
  changed_when: false

# tirar o tracker do inicio do gnome
#/etc/xdg/autostart/tracker-
- name: Disable popularity-contest
  lineinfile:
    dest: /etc/xdg/autostart/{{ item }}
    regexp: '^X-GNOME-Autostart-enabled'
    line: 'X-GNOME-Autostart-enabled=false'
    state: present
  with_items:
    - tracker-extract.desktop
    - tracker-miner-fs.desktop
    - tracker-store.desktop
  become: true
